// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoJ5XxaqB81z_RWZwv0Xn4416MI8IW-rA',
    appId: '1:240816103560:web:e4b9660c383c57e0b57f3d',
    messagingSenderId: '240816103560',
    projectId: 'pfeapp-5513c',
    authDomain: 'pfeapp-5513c.firebaseapp.com',
    storageBucket: 'pfeapp-5513c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-F7Xyf470qZ_LUbQAJ010JS4zQR1KmUM',
    appId: '1:240816103560:android:78f5ce1e609fb3f7b57f3d',
    messagingSenderId: '240816103560',
    projectId: 'pfeapp-5513c',
    storageBucket: 'pfeapp-5513c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFybMW95gB_QLB4a0x3g1BK_WdGV3L5iI',
    appId: '1:240816103560:ios:e6c6ea547bc3a58bb57f3d',
    messagingSenderId: '240816103560',
    projectId: 'pfeapp-5513c',
    storageBucket: 'pfeapp-5513c.appspot.com',
    iosClientId:
        '240816103560-n8t7mdgqhdo8pappjlff0uqh9oi6tui1.apps.googleusercontent.com',
    iosBundleId: 'com.example.essai2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFybMW95gB_QLB4a0x3g1BK_WdGV3L5iI',
    appId: '1:240816103560:ios:e6c6ea547bc3a58bb57f3d',
    messagingSenderId: '240816103560',
    projectId: 'pfeapp-5513c',
    storageBucket: 'pfeapp-5513c.appspot.com',
    iosClientId:
        '240816103560-n8t7mdgqhdo8pappjlff0uqh9oi6tui1.apps.googleusercontent.com',
    iosBundleId: 'com.example.essai2',
  );
}
